version: '3.4'

services:
  antivirus:
    image: mkodockx/docker-clamav:alpine
    ports:
      - "3310:3310"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672


  smartenergyusers:
    image: ${DOCKER_REGISTRY-}smartenergyusers
    build:
      context: .
      dockerfile: SmartEnergyUsers/Dockerfile
    ports:
      - "54000:50001"
      - "44372:80"
    depends_on:
      - users-db
      - rabbitmq

  users-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1401:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your+password123"


  physical-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1402:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your+password123"


  smartenergyusers-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "smartenergyusers", "-app-port", "80", "-components-path", "/components" ]
    depends_on:
      - smartenergyusers
    volumes:
      - "./components/:/components"
    network_mode: "service:smartenergyusers"

  smartenergyphysical:
    image: ${DOCKER_REGISTRY-}smartenergyphysical
    build:
      context: .
      dockerfile: SmartEnergyPhysical/Dockerfile
    ports:
      - "52000:50001"
      - "44373:80"
    depends_on:
      - physical-db
      - rabbitmq

  smartenergyphysical-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "smartenergyphysical", "-app-port", "80", "-components-path", "/components" ]
    depends_on:
      - smartenergyphysical
    volumes:
      - "./components/:/components"
    network_mode: "service:smartenergyphysical"


  smartenergydocuments:
    image: ${DOCKER_REGISTRY-}smartenergydocuments
    build:
      context: .
      dockerfile: SmartEnergyDocuments/Dockerfile
    ports:
      - "53000:50001"
      - "44374:80"
    depends_on:
      - documents-db
      - rabbitmq


  documents-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1403:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your+password123"



  smartenergydocuments-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "smartenergydocuments", "-app-port", "80", "-components-path", "/components" ]
    depends_on:
      - smartenergydocuments
    network_mode: "service:smartenergydocuments"
    volumes:
      - "./components/:/components"
